### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by Brianchat** [passlock-dev/passkeys#2]
Trying to register but getting error that credential cannot be created.

![image](https://github.com/passlock-dev/passkeys/assets/1737789/fc0f3376-27d5-46a3-80e0-2563dd1ba25e)

**Comment by thobson** [comment]
Hi Brian, thanks for reporting this. 

Please can you tell me which OS and browser you're using?

**Comment by Brianchat** [comment]
Chrome v124.0.6367.203   on Windows 11 Home, OS build 22631.3593

**Comment by thobson** [comment]
Thanks, I'll try to recreate at my end.

**Comment by thobson** [comment]
I think I know what's causing this. I will try to get a fix in place this weekend. Thanks again for reporting.
